@startuml sortByDurationSequence

Actor User
participant driver
participant Comparator
participant PathResultCatalog

User -> driver: sortByDuration()
driver -> Comparator : cmp-:create()
driver -> PathResultCatalog : pathResults-:sort(cmp)
driver -> driver : display(pathResults)

@enduml